# Generated by Django 4.2.16 on 2024-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0002_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="business_registration_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="contact_phone_number",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="hotel_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="meal_plan",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="rate",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="room_id",
            field=models.IntegerField(),
        ),
    ]
