# Generated by Django 4.2.16 on 2024-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0003_alter_hotel_business_registration_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(default="melbourne", max_length=255),
        ),
    ]
