# Generated by Django 4.2.16 on 2024-09-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0005_booking_personal_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personal_data",
            old_name="address",
            new_name="billing_address",
        ),
        migrations.AddField(
            model_name="personal_data",
            name="email",
            field=models.CharField(default=" ", max_length=30),
        ),
        migrations.AddField(
            model_name="personal_data",
            name="shipping_address",
            field=models.CharField(default=" ", max_length=100),
        ),
    ]
