# Generated by Django 4.2.16 on 2024-09-19 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0006_rename_address_personal_data_billing_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="check_in_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
