# Generated by Django 4.2.16 on 2024-09-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0008_remove_booking_id_booking_booking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
