# Generated by Django 4.2.16 on 2024-10-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0010_booking_creation_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.IntegerField()),
                ("hotel_name", models.CharField(max_length=100)),
                ("rate", models.IntegerField()),
                ("supplier_contract_name", models.CharField(max_length=100)),
                ("contact_phone_number", models.CharField(max_length=15)),
                ("business_registration_number", models.CharField(max_length=100)),
                ("hotel_url", models.URLField()),
                ("meal_plan", models.CharField(max_length=100)),
                ("address", models.CharField(default="melbourne", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Room_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.IntegerField()),
                ("room_id", models.IntegerField()),
                ("room_type", models.CharField(max_length=40)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Room_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.IntegerField()),
                ("room_image", models.ImageField(upload_to="")),
            ],
        ),
    ]
