# Generated by Django 4.2.16 on 2024-10-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0011_hotel_data_room_data_room_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel_data",
            name="id",
        ),
        migrations.RemoveField(
            model_name="room_data",
            name="id",
        ),
        migrations.AlterField(
            model_name="hotel_data",
            name="hotel_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room_data",
            name="room_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
