# Generated by Django 4.2.16 on 2024-10-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_booking", "0012_remove_hotel_data_id_remove_room_data_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room_data",
            name="inventory",
            field=models.IntegerField(default=0),
        ),
    ]
