# Generated by Django 5.1.1 on 2024-10-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_booking', '0014_room_data_room_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room_image',
        ),
        migrations.AlterField(
            model_name='hotel_data',
            name='hotel_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room_data',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AlterUniqueTogether(
            name='room_data',
            unique_together={('hotel_id', 'room_type')},
        ),
    ]
